//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net48MvcRenshuModeling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string student_no { get; set; }
        public string sei { get; set; }
        public string mei { get; set; }
        public string sei_kana { get; set; }
        public string mei_kana { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public string blood_type { get; set; }
        public string gender { get; set; }
        public string phone { get; set; }
        public string postal_code { get; set; }
        public string addr_pref { get; set; }
        public string addr_city { get; set; }
        public string addr_street { get; set; }
        public string addr_building { get; set; }
        public string addr_pref_kana { get; set; }
        public string addr_city_kana { get; set; }
        public string addr_street_kana { get; set; }
        public string addr_building_kana { get; set; }
    }
}
